backend:
  name: github
  repo: pikounis/eleonora
  branch: master
  api_root: https://api.github.com
  site_domain: localhost:3000
  base_url: https://api.netlify.com
  auth_endpoint: auth
  publish_mode: editorial_workflow

#media_folder: 'src/assets/photos'
media_folder: 'public/images'
public_folder: 'images'

collections:
  - name: gallery
    label: Gallery
    files:
      - file: src/data/gallery.json
        name: gallery_content
        label: 'Gallery Content'
        fields:
          - label: "Gallery"
            name: "galleryImages"
            widget: "list"
            summary: '{{fields.image}}'
            fields:
              - label: 'Artwork'
                name: author
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Description, name: description, widget: string}
                  - {label: Photo, name: photo, widget: image}
